sudo: false
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="https://github.com/django/django/tarball/stable/1.9.x#egg=django"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.5"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.5"
      env: DJANGO="django>=1.5,<1.6"
    - python: "3.5"
      env: DJANGO="django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO="django>=1.7,<1.8"
    - python: "3.5"
      env: DJANGO="django>=1.8,<1.9"
    - python: "3.4"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.4"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.3"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO="https://github.com/django/django/tarball/stable/1.9.x#egg=django"
    - python: "2.6"
      env: DJANGO="django>=1.5,<1.6"
    - python: "2.6"
      env: DJANGO="django>=1.6,<1.7"
    - python: "2.6"
      env: DJANGO="django>=1.7,<1.8"
    - python: "2.6"
      env: DJANGO="django>=1.8,<1.9"
    - python: "2.6"
      env: DJANGO="https://github.com/django/django/tarball/stable/1.9.x#egg=django"
install:
  - travis_retry pip install --upgrade pip -q
  - travis_retry pip install $DJANGO
  - travis_retry pip install nose coverage flake8 flake8-blind-except flake8-debugger flake8-print flake8-quotes pep8-naming frosted isort coveralls -q
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then travis_retry pip install ujson; fi
script:
  - python setup.py nosetests --with-coverage
after_success:
  - flake8 --show-source redis_sessions_fork
  - frosted -r redis_sessions_fork
  - isort --check-only -rc redis_sessions_fork --diff
  - travis_retry coveralls
